# ---------------------------------------------------------------- #
# CodeRabbit AI 설정
# ---------------------------------------------------------------- #

# 응답 기본 언어 설정
language: "ko-KR"
# AI의 페르소나와 응답 톤앤매너를 상세하게 지시합니다. 최대 200자까지 작성할 수 있습니다.
tone_instructions: >
  1. 피드백은 명확하고 구체적이어야 하며, 문제의 원인과 개선 방법을 반드시 제시하세요.
  2. 리뷰는 교육적이어야 하며, 관련 개념이나 공식 문서를 함께 추천하세요.
  3. 비판보다는 개선 중심의 제안을 우선하세요.
  4. 칭찬은 짧고 위트 있게 작성하세요.

# ---------------------------------------------------------------- #
# 코드 리뷰 기능 세부 설정
# ---------------------------------------------------------------- #
reviews:

  profile: "chill"    # 리뷰의 전반적인 스타일 설정(chill은 비교적 덜 엄격하고 부드러운 톤을 의미)
  request_changes_workflow: false   # CodeRabbit의 코멘트를 모두 `resolve`하면, 자동으로 Approve
  high_level_summary: true  # PR의 전체적인 변경 사항에 대한 고수준의 요약(summary) 생성 여부
  collapse_walkthrough: true  # 워크스루 코멘트를 접을 수 있는 형식으로 게시. PR이 너무 길어지는 걸 방지
  changed_files_summary: true  # 변경된 각 파일에 대한 요약 생성 여부
  sequence_diagrams: true    # 코드의 실행 흐름을 보여주는 시퀀스 다이어그램 생성 여부
  assess_linked_issues: true      # PR에 연결된 이슈를 분석하여 리뷰 컨텍스트에 활용할지 여부
  related_issues: false  # 연관된 다른 이슈를 찾아서 링크할지 여부
  related_prs: true      # 연관된 다른 PR을 찾아서 링크할지 여부
  suggested_labels: false     # PR에 적절한 레이블을 제안할지 여부
  auto_apply_labels: false    # 제안된 레이블을 자동으로 PR에 적용할지 여부
  suggested_reviewers: false      # 이 PR을 리뷰할 만한 적절한 동료 리뷰어를 추천할지 여부
  auto_assign_reviewers: false    # 추천된 리뷰어를 자동으로 할당할지 여부
  poem: true          # 리뷰 요약에 위트 있는 시를 포함할지 여부. 귀여워서 넣었습니다.

  # ---------------------------------------------------------------- #
  # 자동 리뷰 트리거 설정
  # ---------------------------------------------------------------- #
  auto_review:
    enabled: true
    # 이미 리뷰가 진행된 PR에 새로운 커밋이 추가될 때, 변경된 부분에 대해서만 자동으로 리뷰를 진행할지 여부
    auto_incremental_review: true

# ---------------------------------------------------------------- #
# 채팅 기능 설정
# ---------------------------------------------------------------- #
chat:
  # 사용자가 @coderabbitai 태그를 지정하지 않아도 자동으로 답글을 달 수 있도록 설정
  auto_reply: true

# ---------------------------------------------------------------- #
# CodeRabbit의 지식 기반(Knowledge Base) 설정
# ---------------------------------------------------------------- #
knowledge_base:
  # 웹 검색을 통해 최신 정보나 문서를 참조할 수 있도록 허용할지 여부
  web_search:
    enabled: true
  code_guidelines:
    enabled: true
